--[[
   * Author: sockmonkey72
   * Licence: MIT
   * Version: 1.00
   * NoIndex: true
--]]

local GeneralDefs = {}

----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

local DEFAULT_TIMEFORMAT_STRING = '1.1.00'
local DEFAULT_LENGTHFORMAT_STRING = '0.0.00'

local PARAM_TYPE_UNKNOWN = 0
local PARAM_TYPE_MENU = 1
local PARAM_TYPE_INTEDITOR = 2
local PARAM_TYPE_FLOATEDITOR = 3
local PARAM_TYPE_TIME = 4
local PARAM_TYPE_TIMEDUR = 5
local PARAM_TYPE_METRICGRID = 6
local PARAM_TYPE_MUSICAL = 7
local PARAM_TYPE_EVERYN = 8
local PARAM_TYPE_NEWMIDIEVENT = 9
local PARAM_TYPE_PARAM3 = 10
local PARAM_TYPE_EVENTSELECTOR = 11
local PARAM_TYPE_HIDDEN = 12

local EDITOR_TYPE_PITCHBEND = 100
local EDITOR_TYPE_PITCHBEND_BIPOLAR = 101
local EDITOR_TYPE_PERCENT = 102
local EDITOR_TYPE_PERCENT_BIPOLAR = 103
local EDITOR_TYPE_7BIT = 104
local EDITOR_TYPE_7BIT_NOZERO = 105
local EDITOR_TYPE_7BIT_BIPOLAR = 106
local EDITOR_TYPE_14BIT = 107
local EDITOR_TYPE_14BIT_BIPOLAR = 108
local EDITOR_TYPE_BITFIELD = 109

GeneralDefs.INVALID = -0xFFFFFFFF

GeneralDefs.NOTE_TYPE = 0
GeneralDefs.CC_TYPE = 1
GeneralDefs.SYXTEXT_TYPE = 2
GeneralDefs.OTHER_TYPE = 7

GeneralDefs.DEFAULT_TIMEFORMAT_STRING = DEFAULT_TIMEFORMAT_STRING
GeneralDefs.DEFAULT_LENGTHFORMAT_STRING = DEFAULT_LENGTHFORMAT_STRING

GeneralDefs.PARAM_TYPE_UNKNOWN = PARAM_TYPE_UNKNOWN
GeneralDefs.PARAM_TYPE_MENU = PARAM_TYPE_MENU
GeneralDefs.PARAM_TYPE_INTEDITOR = PARAM_TYPE_INTEDITOR
GeneralDefs.PARAM_TYPE_FLOATEDITOR = PARAM_TYPE_FLOATEDITOR
GeneralDefs.PARAM_TYPE_TIME = PARAM_TYPE_TIME
GeneralDefs.PARAM_TYPE_TIMEDUR = PARAM_TYPE_TIMEDUR
GeneralDefs.PARAM_TYPE_METRICGRID = PARAM_TYPE_METRICGRID
GeneralDefs.PARAM_TYPE_MUSICAL = PARAM_TYPE_MUSICAL
GeneralDefs.PARAM_TYPE_EVERYN = PARAM_TYPE_EVERYN
GeneralDefs.PARAM_TYPE_NEWMIDIEVENT = PARAM_TYPE_NEWMIDIEVENT
GeneralDefs.PARAM_TYPE_PARAM3 = PARAM_TYPE_PARAM3
GeneralDefs.PARAM_TYPE_EVENTSELECTOR = PARAM_TYPE_EVENTSELECTOR
GeneralDefs.PARAM_TYPE_HIDDEN = PARAM_TYPE_HIDDEN

GeneralDefs.EDITOR_TYPE_PITCHBEND = EDITOR_TYPE_PITCHBEND
GeneralDefs.EDITOR_PITCHBEND_RANGE = { -(1 << 13), (1 << 13) - 1 }
GeneralDefs.EDITOR_TYPE_PITCHBEND_BIPOLAR = EDITOR_TYPE_PITCHBEND_BIPOLAR
GeneralDefs.EDITOR_PITCHBEND_BIPOLAR_RANGE = { -((1 << 14) - 1), (1 << 14) - 1 }
GeneralDefs.EDITOR_TYPE_PERCENT = EDITOR_TYPE_PERCENT
GeneralDefs.EDITOR_PERCENT_RANGE = { 0, 100 }
GeneralDefs.EDITOR_TYPE_PERCENT_BIPOLAR = EDITOR_TYPE_PERCENT_BIPOLAR
GeneralDefs.EDITOR_PERCENT_BIPOLAR_RANGE = { -100, 100 }
GeneralDefs.EDITOR_TYPE_7BIT = EDITOR_TYPE_7BIT
GeneralDefs.EDITOR_7BIT_RANGE = { 0, (1 << 7) - 1 }
GeneralDefs.EDITOR_TYPE_7BIT_NOZERO = EDITOR_TYPE_7BIT_NOZERO
GeneralDefs.EDITOR_7BIT_NOZERO_RANGE = { 1, (1 << 7) - 1 }
GeneralDefs.EDITOR_TYPE_7BIT_BIPOLAR = EDITOR_TYPE_7BIT_BIPOLAR
GeneralDefs.EDITOR_7BIT_BIPOLAR_RANGE = { -((1 << 7) - 1), (1 << 7) - 1 }
GeneralDefs.EDITOR_TYPE_14BIT = EDITOR_TYPE_14BIT
GeneralDefs.EDITOR_14BIT_RANGE = { 0, (1 << 14) - 1 }
GeneralDefs.EDITOR_TYPE_14BIT_BIPOLAR = EDITOR_TYPE_14BIT_BIPOLAR
GeneralDefs.EDITOR_14BIT_BIPOLAR_RANGE = { -((1 << 14) - 1), (1 << 14) - 1 }

GeneralDefs.EDITOR_TYPE_BITFIELD = EDITOR_TYPE_BITFIELD

GeneralDefs.CC_CURVE_SQUARE = 0
GeneralDefs.CC_CURVE_LINEAR = 1
GeneralDefs.CC_CURVE_SLOW_START_END = 2
GeneralDefs.CC_CURVE_FAST_START = 3
GeneralDefs.CC_CURVE_FAST_END = 4
GeneralDefs.CC_CURVE_BEZIER = 5

GeneralDefs.MG_GRID_STRAIGHT = 0
GeneralDefs.MG_GRID_DOTTED = 1
GeneralDefs.MG_GRID_TRIPLET = 2
GeneralDefs.MG_GRID_SWING = 3
GeneralDefs.MG_GRID_SWING_REAPER = 0x8

return GeneralDefs
