--[[
   * Author: sockmonkey72
   * Licence: MIT
   * Version: 1.00
   * NoIndex: true
--]]

package.path = debug.getinfo(1, 'S').source:match [[^@?(.*[\/])[^\/]-$]] .. '/?.lua;' -- GET DIRECTORY FOR REQUIRE
local helper = require 'MIDIRazorEdits_Helper'

local Keys = {}

local vKeys = {
  VK_LBUTTON 	    = 0x01,   --  The left mouse button
  VK_RBUTTON 	    = 0x02,   --  The right mouse button
  VK_CANCEL 	    = 0x03,   --  The Cancel virtual key, used for control-break processing
  VK_MBUTTON 	    = 0x04,   --  The middle mouse button
  VK_BACK 	      = 0x08,   --  Backspace
  VK_TAB 	        = 0x09,   --  Tab
  VK_CLEAR 	      = 0x0C,   --  5 (keypad without Num Lock)
  VK_ENTER   	    = 0x0D,   --  Enter
  VK_SHIFT 	      = 0x10,   --  Shift (either one)
  VK_CONTROL 	    = 0x11,   --  Ctrl (either one)
  VK_MENU         = 0x12,   --  Alt (either one)
  VK_PAUSE        = 0x13,   --  Pause
  VK_CAPITAL 	    = 0x14,   --  Caps Lock
  VK_ESCAPE 	    = 0x1B,   --  Esc
  VK_SPACE 	      = 0x20,   --  Spacebar
  VK_PAGEUP 	    = 0x21,   --  Page Up
  VK_PAGEDOWN 	  = 0x22,   --  Page Down
  VK_END 	        = 0x23,   --  End
  VK_HOME 	      = 0x24,   --  Home
  VK_LEFT 	      = 0x25,   --  Left Arrow
  VK_UP 	        = 0x26,   --  Up Arrow
  VK_RIGHT 	      = 0x27,   --  Right Arrow
  VK_DOWN 	      = 0x28,   --  Down Arrow
  VK_SELECT 	    = 0x29,   --  Select
  VK_PRINT 	      = 0x2A,   --  Print (only used by Nokia keyboards)
  VK_EXECUTE 	    = 0x2B,   --  Execute (not used)
  VK_SNAPSHOT 	  = 0x2C,   --  Print Screen
  VK_INSERT 	    = 0x2D,   --  Insert
  VK_DELETE 	    = 0x2E,   --  Delete
  VK_HELP 	      = 0x2F,   --  Help
  VK_0 	          = 0x30,   --  0
  VK_1 	          = 0x31,   --  1
  VK_2 	          = 0x32,   --  2
  VK_3 	          = 0x33,   --  3
  VK_4 	          = 0x34,   --  4
  VK_5 	          = 0x35,   --  5
  VK_6 	          = 0x36,   --  6
  VK_7 	          = 0x37,   --  7
  VK_8 	          = 0x38,   --  8
  VK_9 	          = 0x39,   --  9
  VK_A 	          = 0x41,   --  A
  VK_B 	          = 0x42,   --  B
  VK_C 	          = 0x43,   --  C
  VK_D 	          = 0x44,   --  D
  VK_E 	          = 0x45,   --  E
  VK_F 	          = 0x46,   --  F
  VK_G 	          = 0x47,   --  G
  VK_H 	          = 0x48,   --  H
  VK_I 	          = 0x49,   --  I
  VK_J 	          = 0x4A,   --  J
  VK_K 	          = 0x4B,   --  K
  VK_L 	          = 0x4C,   --  L
  VK_M 	          = 0x4D,   --  M
  VK_N 	          = 0x4E,   --  N
  VK_O 	          = 0x4F,   --  O
  VK_P 	          = 0x50,   --  P
  VK_Q 	          = 0x51,   --  Q
  VK_R 	          = 0x52,   --  R
  VK_S 	          = 0x53,   --  S
  VK_T 	          = 0x54,   --  T
  VK_U 	          = 0x55,   --  U
  VK_V 	          = 0x56,   --  V
  VK_W 	          = 0x57,   --  W
  VK_X 	          = 0x58,   --  X
  VK_Y 	          = 0x59,   --  Y
  VK_Z 	          = 0x5A,   --  Z
  VK_STARTKEY 	  = 0x5B,   --  Start Menu key
  VK_CONTEXTKEY 	= 0x5D,   --  Context Menu key
  VK_NUMPAD0 	    = 0x60,   --  0 (keypad with Num Lock)
  VK_NUMPAD1 	    = 0x61,   --  1 (keypad with Num Lock)
  VK_NUMPAD2 	    = 0x62,   --  2 (keypad with Num Lock)
  VK_NUMPAD3 	    = 0x63,   --  3 (keypad with Num Lock)
  VK_NUMPAD4 	    = 0x64,   --  4 (keypad with Num Lock)
  VK_NUMPAD5 	    = 0x65,   --  5 (keypad with Num Lock)
  VK_NUMPAD6 	    = 0x66,   --  6 (keypad with Num Lock)
  VK_NUMPAD7 	    = 0x67,   --  7 (keypad with Num Lock)
  VK_NUMPAD8 	    = 0x68,   --  8 (keypad with Num Lock)
  VK_NUMPAD9 	    = 0x69,   --  9 (keypad with Num Lock)
  VK_MULTIPLY 	  = 0x6A,   --  * (keypad)
  VK_ADD 	        = 0x6B,   --  = 0x(keypad)
  VK_SEPARATOR 	  = 0x6C,   --  Separator (never generated by the keyboard)
  VK_SUBTRACT 	  = 0x6D,   --  - (keypad)
  VK_DECIMAL 	    = 0x6E,   --  . (keypad with Num Lock)
  VK_DIVIDE 	    = 0x6F,   --  / (keypad)
  VK_F1 	        = 0x70,   --  F1
  VK_F2 	        = 0x71,   --  F2
  VK_F3 	        = 0x72,   --  F3
  VK_F4 	        = 0x73,   --  F4
  VK_F5 	        = 0x74,   --  F5
  VK_F6 	        = 0x75,   --  F6
  VK_F7 	        = 0x76,   --  F7
  VK_F8 	        = 0x77,   --  F8
  VK_F9 	        = 0x78,   --  F9
  VK_F10 	        = 0x79,   --  F10
  VK_F11 	        = 0x7A,   --  F11
  VK_F12 	        = 0x7B,   --  F12
  VK_F13 	        = 0x7C,   --  F13
  VK_F14 	        = 0x7D,   --  F14
  VK_F15 	        = 0x7E,   --  F15
  VK_F16 	        = 0x7F,   --  F16
  VK_F17 	        = 0x80,   --  F17
  VK_F18 	        = 0x81,   --  F18
  VK_F19 	        = 0x82,   --  F19
  VK_F20 	        = 0x83,   --  F20
  VK_F21 	        = 0x84,   --  F21
  VK_F22 	        = 0x85,   --  F22
  VK_F23 	        = 0x86,   --  F23
  VK_F24 	        = 0x87,   --  F24
  VK_NUMLOCK 	    = 0x90,   --  Num Lock
  VK_OEM_SCROLL 	= 0x91,   --  Scroll Lock
  VK_OEM_1 	      = 0xBA,   --  ;
  VK_OEM_PLUS 	  = 0xBB,   --  =
  VK_OEM_COMMA 	  = 0xBC,   --  ,
  VK_OEM_MINUS 	  = 0xBD,   --  -
  VK_OEM_PERIOD 	= 0xBE,   --  .
  VK_OEM_2 	      = 0xBF,   --  /
  VK_OEM_3 	      = 0xC0,   --  `
  VK_OEM_4 	      = 0xDB,   --  [
  VK_OEM_5 	      = 0xDC,   --  \
  VK_OEM_6 	      = 0xDD,   --  ]
  VK_OEM_7 	      = 0xDE,   --  '
  VK_OEM_8 	      = 0xDF,   --  (unknown)
  VK_ICO_F17 	    = 0xE0,   --  F17 on Olivetti extended keyboard (internal use only)
  VK_ICO_F18 	    = 0xE1,   --  F18 on Olivetti extended keyboard (internal use only)
  VK_OEM_102 	    = 0xE2,   --  < or | on IBM-compatible 102 enhanced non-U.S. keyboard
  VK_ICO_HELP 	  = 0xE3,   --  Help on Olivetti extended keyboard (internal use only)
  VK_ICO_00 	    = 0xE4,   --  00 on Olivetti extended keyboard (internal use only)
  VK_ICO_CLEAR 	  = 0xE6,   --  Clear on Olivette extended keyboard (internal use only)
  VK_OEM_RESET 	  = 0xE9,   --  Reset (Nokia keyboards only)
  VK_OEM_JUMP 	  = 0xEA,   --  Jump (Nokia keyboards only)
  VK_OEM_PA1 	    = 0xEB,   --  PA1 (Nokia keyboards only)
  VK_OEM_PA2 	    = 0xEC,   --  PA2 (Nokia keyboards only)
  VK_OEM_PA3 	    = 0xED,   --  PA3 (Nokia keyboards only)
  VK_OEM_WSCTRL 	= 0xEE,   --  WSCTRL (Nokia keyboards only)
  VK_OEM_CUSEL 	  = 0xEF,   --  CUSEL (Nokia keyboards only)
  VK_OEM_ATTN 	  = 0xF0,   --  ATTN (Nokia keyboards only)
  VK_OEM_FINNISH 	= 0xF1,   --  FINNISH (Nokia keyboards only)
  VK_OEM_COPY 	  = 0xF2,   --  COPY (Nokia keyboards only)
  VK_OEM_AUTO 	  = 0xF3,   --  AUTO (Nokia keyboards only)
  VK_OEM_ENLW 	  = 0xF4,   --  ENLW (Nokia keyboards only)
  VK_OEM_BACKTAB 	= 0xF5,   --  BACKTAB (Nokia keyboards only)
  VK_ATTN 	      = 0xF6,   --  ATTN
  VK_CRSEL 	      = 0xF7,   --  CRSEL
  VK_EXSEL 	      = 0xF8,   --  EXSEL
  VK_EREOF 	      = 0xF9,   --  EREOF
  VK_PLAY 	      = 0xFA,   --  PLAY
  VK_ZOOM 	      = 0xFB,   --  ZOOM
  VK_NONAME 	    = 0xFC,   --  NONAME
  VK_PA1 	        = 0xFD,   --  PA1
  VK_OEM_CLEAR 	  = 0xFE,   --  CLEAR
}

-- if helper.is_macos then -- is wrong, and they don't fire consistently
--   vKeys.VK_OEM_1      = 41 -- ;
--   vKeys.VK_OEM_PLUS   = 24 -- =
--   vKeys.VK_OEM_MINUS  = 27 -- -
--   vKeys.VK_OEM_COMMA  = 43 -- ,
--   vKeys.VK_OEM_PERIOD = 47 -- .
--   vKeys.VK_OEM_2      = 44 -- /
--   vKeys.VK_OEM_3      = 50 -- `
--   vKeys.VK_OEM_4      = 33 -- [
--   vKeys.VK_OEM_5      = 42 -- \
--   vKeys.VK_OEM_6      = 30 -- ]
--   vKeys.VK_OEM_7      = 39 -- '
-- end

Keys.vKeys = vKeys

local vKeyLookup = {
  ['0'] = vKeys.VK_0,
  ['1'] = vKeys.VK_1,
  ['2'] = vKeys.VK_2,
  ['3'] = vKeys.VK_3,
  ['4'] = vKeys.VK_4,
  ['5'] = vKeys.VK_5,
  ['6'] = vKeys.VK_6,
  ['7'] = vKeys.VK_7,
  ['8'] = vKeys.VK_8,
  ['9'] = vKeys.VK_9,

  num_0 = vKeys.VK_NUMPAD0,
  num_1 = vKeys.VK_NUMPAD1,
  num_2 = vKeys.VK_NUMPAD2,
  num_3 = vKeys.VK_NUMPAD3,
  num_4 = vKeys.VK_NUMPAD4,
  num_5 = vKeys.VK_NUMPAD5,
  num_6 = vKeys.VK_NUMPAD6,
  num_7 = vKeys.VK_NUMPAD7,
  num_8 = vKeys.VK_NUMPAD8,
  num_9 = vKeys.VK_NUMPAD9,

  num_mult = vKeys.VK_MULTIPLY,
  num_add = vKeys.VK_ADD,
  num_sub = vKeys.VK_SUBTRACT,
  num_period = vKeys.VK_DECIMAL,
  num_div = vKeys.VK_DIVIDE,

  F1 = vKeys.VK_F1,
  F2 = vKeys.VK_F2,
  F3 = vKeys.VK_F3,
  F4 = vKeys.VK_F4,
  F5 = vKeys.VK_F5,
  F6 = vKeys.VK_F6,
  F7 = vKeys.VK_F7,
  F8 = vKeys.VK_F8,
  F9 = vKeys.VK_F9,
  F10 = vKeys.VK_F10,
  F11 = vKeys.VK_F11,
  F12 = vKeys.VK_F12,
  F13 = vKeys.VK_F13,
  F14 = vKeys.VK_F14,
  F15 = vKeys.VK_F15,
  F16 = vKeys.VK_F16,
  F17 = vKeys.VK_F17,
  F18 = vKeys.VK_F18,
  F19 = vKeys.VK_F19,
  F20 = vKeys.VK_F20,
  F21 = vKeys.VK_F21,
  F22 = vKeys.VK_F22,
  F23 = vKeys.VK_F23,
  F24 = vKeys.VK_F24,

  a = vKeys.VK_A,
  b = vKeys.VK_B,
  c = vKeys.VK_C,
  d = vKeys.VK_D,
  e = vKeys.VK_E,
  f = vKeys.VK_F,
  g = vKeys.VK_G,
  h = vKeys.VK_H,
  i = vKeys.VK_I,
  j = vKeys.VK_J,
  k = vKeys.VK_K,
  l = vKeys.VK_L,
  m = vKeys.VK_M,
  n = vKeys.VK_N,
  o = vKeys.VK_O,
  p = vKeys.VK_P,
  q = vKeys.VK_Q,
  r = vKeys.VK_R,
  s = vKeys.VK_S,
  t = vKeys.VK_T,
  u = vKeys.VK_U,
  v = vKeys.VK_V,
  w = vKeys.VK_W,
  x = vKeys.VK_X,
  y = vKeys.VK_Y,
  z = vKeys.VK_Z,

  esc = vKeys.VK_ESCAPE,
  space = vKeys.VK_SPACE,
  del = vKeys.VK_DELETE,
  back = vKeys.VK_BACK,
  up = vKeys.VK_UP,
  down = vKeys.VK_DOWN,
  left = vKeys.VK_LEFT,
  right = vKeys.VK_RIGHT,

  semi = vKeys.VK_OEM_1,
  equals = vKeys.VK_OEM_PLUS,
  comma = vKeys.VK_OEM_COMMA,
  minus = vKeys.VK_OEM_MINUS,
  period = vKeys.VK_OEM_PERIOD,
  slash = vKeys.VK_OEM_2,
  backtick = vKeys.VK_OEM_3,
  openbracket = vKeys.VK_OEM_4,
  backslash = vKeys.VK_OEM_5,
  closebracket = vKeys.VK_OEM_6,
  quote = vKeys.VK_OEM_7,

  -- A = vKeys.VK_A,
  -- B = vKeys.VK_B,
  -- C = vKeys.VK_C,
  -- D = vKeys.VK_D,
  -- E = vKeys.VK_E,
  -- F = vKeys.VK_F,
  -- G = vKeys.VK_G,
  -- H = vKeys.VK_H,
  -- I = vKeys.VK_I,
  -- J = vKeys.VK_J,
  -- K = vKeys.VK_K,
  -- L = vKeys.VK_L,
  -- M = vKeys.VK_M,
  -- N = vKeys.VK_N,
  -- O = vKeys.VK_O,
  -- P = vKeys.VK_P,
  -- Q = vKeys.VK_Q,
  -- R = vKeys.VK_R,
  -- S = vKeys.VK_S,
  -- T = vKeys.VK_T,
  -- U = vKeys.VK_U,
  -- V = vKeys.VK_V,
  -- W = vKeys.VK_W,
  -- X = vKeys.VK_X,
  -- Y = vKeys.VK_Y,
  -- Z = vKeys.VK_Z,
}

-- (Win/Lin: add 1 for shift, 2 for control, 4 for alt, 8 for win.)
-- (macOS: add 1 for shift, 2 for command, 4 for opt, 8 for control.)

local defaultKeyMappings = {
  duplicate           = { name = 'Duplicate Area(s), Moving Area',      baseKey = 'd', testOverlap = true },
  ccSpan              = { name = 'Span Area across CC Lanes',           baseKey = 'c', noteOnly = true },
  fullLane            = { name = 'Set Full Lane',                       baseKey = 'f' },
  invert              = { name = 'Invert Contents',                     baseKey = 'v', testOverlap = true },
  retrograde          = { name = 'Reverse Contents',                    baseKey = 'r', testOverlap = true },
  retrograde2         = { name = 'Reverse Values, Preserving Position', baseKey = 'r', modifiers = 1, testOverlap = true },
  select              = { name = 'Select Contents',                     baseKey = 's', testOverlap = true },
  unselect            = { name = 'Unselect Contents',                   baseKey = 'u', testOverlap = true },
  deleteAreaContents  = { name = 'Delete Area and Contents',            baseKey = 'del', testOverlap = true },
  deleteArea          = { name = 'Delete Area, Preserve Contents',      baseKey = 'x', modifiers = 1 },
  deleteContents      = { name = 'Delete Contents',                     baseKey = 'x', testOverlap = true },
  widgetMode          = { name = 'Toggle Widget Mode',                  baseKey = 'w' },
  insertMode          = { name = 'Toggle Insert Mode',                  baseKey = 'i' },
  horzLockMode        = { name = 'Toggle Horizontal Lock Mode',         baseKey = 'h' },
  vertLockMode        = { name = 'Toggle Vertical Lock Mode',           baseKey = 'l' },
  exitScript          = { name = 'Exit MRE',                            baseKey = 'esc', global = true },
  cut                 = { name = 'Cut Area',                            baseKey = 'x', modifiers = 2 },
  copy                = { name = 'Copy Area',                           baseKey = 'c', modifiers = 2 },
  paste               = { name = 'Paste Area',                          baseKey = 'v', modifiers = 2, global = true },
  shiftleft           = { name = 'Shift Area Left',                     baseKey = 'left' },
  shiftright          = { name = 'Shift Area Right',                    baseKey = 'right' },
  shiftleftgrid       = { name = 'Shift Area Left (Grid)',              baseKey = 'left', modifiers = 3 },
  shiftrightgrid      = { name = 'Shift Area Right (Grid)',             baseKey = 'right', modifiers = 3 },
  shiftleftgridq      = { name = 'Shift Area Left (Grid, Quantized)',   baseKey = 'left', modifiers = 2 },
  shiftrightgridq     = { name = 'Shift Area Right (Grid, Quantized)',  baseKey = 'right', modifiers = 2 },
  slicerMode          = { name = 'Toggle Slicer Mode',                  baseKey = 'z', global = true },
  pitchBendMode       = { name = 'Toggle Pitch Bend Mode',              baseKey = 'p', global = true },
}

-- PB mode keys (separate table, no conflict checking with main keys)
local defaultPbKeyMappings = {
  pitchBendCurveType  = { name = 'Set Curve Type',                      baseKey = 'c' },
  pitchBendSnapSemi   = { name = 'Snap Selected to Semitone',           baseKey = 'q' },
  pitchBendConfig     = { name = 'Project Bend Config',                 baseKey = 'b' },
  pitchBendMicrotonal = { name = 'Toggle Microtonal Lines',             baseKey = 'm' },
  pitchBendChannel    = { name = 'Select Active Channel',               baseKey = 'h' },
  pitchBendSelectAll  = { name = 'Select All Points',                   baseKey = 'a' },
  pitchBendCopy       = { name = 'Copy Points',                         baseKey = 'c', modifiers = 2 },
  pitchBendPaste      = { name = 'Paste Points',                        baseKey = 'v', modifiers = 2 },
}

if helper.is_windows then
  defaultKeyMappings.compositingSetup = { name = 'Open Compositing Tweaks Dialog', baseKey = 'F10', modifiers = 6 }
end

Keys.MODTYPE_SNAP = 1

Keys.MODTYPE_MOVE_COPY = 2
Keys.MODTYPE_MOVE_OVERLAP = 3
Keys.MODTYPE_MOVE_SINGLE = 4
Keys.MODTYPE_MOVE_ONLYAREA = 5

Keys.MODTYPE_NEW_PRESERVE = 6
Keys.MODTYPE_NEW_FULLLANE = 7

Keys.MODTYPE_STRETCH = 8

Keys.MODTYPE_CLICK_SETCURSOR = 9

-- SLICER

Keys.MODTYPE_SLICER_TRIM = 10
Keys.MODTYPE_SLICER_END = 11
Keys.MODTYPE_SLICER_VERTLOCK = 12

-- SLICER

-- PITCH BEND

Keys.MODTYPE_PB_DRAW = 13
Keys.MODTYPE_PB_COMPEXP = 14
Keys.MODTYPE_PB_SNAP_PITCH = 15

-- PITCH BEND

--[[
  1 = shift
  2 = ctrl
  4 = alt
  8 = super
--]]

local defaultModMappings = {
  { name = 'Toggle Snap',               modKey = 1 },

  { name = 'Copy',                      modKey = 2, cat = 'move' },
  { name = 'Preserve Overlaps (notes)', modKey = 4, cat = 'process' },
  { name = 'Single Area',               modKey = 8, cat = 'move' },
  { name = 'Move Area Only',            modKey = 15, cat = 'move', check = true },

  { name = 'Preserve Existing',         modKey = 2, cat = 'new' },
  { name = 'Toggle Full-Lane',          modKey = 4, cat = 'new' },

  { name = 'Stretch Area',              modKey = 4, cat = 'stretch' },

  { name = 'Set Cursor',                modKey = 2, cat = 'click' },

-- SLICER

  { name = 'Trim When Slicing',         modKey = 4, cat = 'slicer' },
  { name = 'Slice Selects/Trims End',   modKey = 8, cat = 'slicer' },
  { name = 'Slice Vertical Lock',       modKey = 2, cat = 'slicer' }, -- or use vertLockMode? mod is more practical here...

-- SLICER

-- PITCH BEND

  { name = 'Draw Mode',                 modKey = 2, cat = 'pb' },
  { name = 'Compress/Expand',           modKey = 8, cat = 'pb' },
  { name = 'Snap to Pitch',             modKey = 4, cat = 'pb' },

-- PITCH BEND

}

Keys.WIDGET_MODE_PUSHPULL = 1
Keys.WIDGET_MODE_OFFSET = 2
Keys.WIDGET_MODE_COMPEXPMID = 3
Keys.WIDGET_MODE_COMPEXPTB = 4

local defaultWidgetMappings = {
  { name = 'Push/Pull',           modKey = 0 },
  { name = 'Offset',              modKey = 1 },
  { name = 'Comp/Exp Middle',     modKey = 4 },
  { name = 'Comp/Exp',            modKey = 2 },
}

Keys.defaultKeyMappings = defaultKeyMappings
Keys.defaultPbKeyMappings = defaultPbKeyMappings
Keys.defaultModMappings = defaultModMappings
Keys.defaultWidgetMappings = defaultWidgetMappings
Keys.vKeyLookup = vKeyLookup

local keyMappings
local pbKeyMappings
local modMappings
local widgetMappings

local userKeyMappings
local userPbKeyMappings
local userModMappings
local userWidgetMappings

local function buildNewKeyMap()
  keyMappings = tableCopy(defaultKeyMappings)
  if userKeyMappings then
    for k, map in pairs(userKeyMappings) do
      if keyMappings[k] then
        keyMappings[k] = map -- pre-vetted
      end
    end
  end
  keyMappings.enterKey = { name = 'Enter Key', baseKey = 'enter', vKey = vKeys.VK_ENTER } -- always listen to enter

  for k, map in pairs(keyMappings) do
    map.vKey = map.vKey or vKeyLookup[map.baseKey]
  end

  pbKeyMappings = tableCopy(defaultPbKeyMappings)
  if userPbKeyMappings then
    for k, map in pairs(userPbKeyMappings) do
      if pbKeyMappings[k] then
        pbKeyMappings[k] = map
      end
    end
  end

  for k, map in pairs(pbKeyMappings) do
    map.vKey = map.vKey or vKeyLookup[map.baseKey]
  end

  modMappings = tableCopy(defaultModMappings)
  if userModMappings then
    for k, map in pairs(userModMappings) do
      if modMappings[k] and map.modKey then
        modMappings[k].modKey = map.modKey
      end
    end
  end

  widgetMappings = tableCopy(defaultWidgetMappings)
  if userWidgetMappings then
    for k, map in pairs(userWidgetMappings) do
      if widgetMappings[k] and map.modKey then
        widgetMappings[k].modKey = map.modKey
      end
    end
  end

  return keyMappings, pbKeyMappings, modMappings, widgetMappings
end

local function loadKeyMappingState(stateTab)
  if userKeyMappings then userKeyMappings = nil end
  if stateTab then
    for k, map in pairs(stateTab) do
      if map.baseKey then
        local vKey = vKeyLookup[map.baseKey]
        if vKey then
          if not userKeyMappings then userKeyMappings = {} end
          userKeyMappings[k] = { baseKey = map.baseKey, modifiers = map.modifiers, vKey = vKey } -- need to ensure that there are no duplicate key/modifiers pairs
        end
      end
    end
  end
end

local function loadPbKeyMappingState(stateTab)
  if userPbKeyMappings then userPbKeyMappings = nil end
  if stateTab then
    for k, map in pairs(stateTab) do
      if map.baseKey then
        local vKey = vKeyLookup[map.baseKey]
        if vKey then
          if not userPbKeyMappings then userPbKeyMappings = {} end
          userPbKeyMappings[k] = { baseKey = map.baseKey, modifiers = map.modifiers, vKey = vKey }
        end
      end
    end
  end
end

local function loadModMappingState(stateTab)
  if userModMappings then userModMappings = nil end
  if stateTab then
    for k, map in pairs(stateTab) do
      if map.modKey then
        if not userModMappings then userModMappings = {} end
        userModMappings[k] = { modKey = map.modKey }
      end
    end
  end
end

local function loadWidgetMappingState(stateTab)
  if userWidgetMappings then userWidgetMappings = nil end
  if stateTab then
    for k, map in pairs(stateTab) do
      if map.modKey then
        if not userWidgetMappings then userWidgetMappings = {} end
        userWidgetMappings[k] = { modKey = map.modKey }
      end
    end
  end
end

Keys.buildNewKeyMap = buildNewKeyMap
Keys.loadKeyMappingState = loadKeyMappingState
Keys.loadPbKeyMappingState = loadPbKeyMappingState
Keys.loadModMappingState = loadModMappingState
Keys.loadWidgetMappingState = loadWidgetMappingState

local mod = {}

local currentMods
local hottestMods

local widgetMods
local forceSnap

mod.setForceSnap = function(way)
  forceSnap = way and true or false
end

mod.getForceSnap = function()
  return forceSnap
end

mod.setMods = function(current, hottest)
  if current then currentMods = current end
  if hottest then hottestMods = hottest end
end

mod.setWidgetMods = function(widget)
  if widget then widgetMods = widget end
end

mod.getMod = function(someMods, modif)
  someMods = someMods or currentMods
  if modif & 1 ~= 0 then return someMods:shift(), 'shift', 'shiftFlag'
  elseif modif & 2 ~= 0 then return someMods:ctrl(), 'ctrl', 'ctrlFlag'
  elseif modif & 4 ~= 0 then return someMods:alt(), 'alt', 'altFlag'
  elseif modif & 8 ~= 0 then return someMods:super(), 'super', 'superFlag'
  end
  return false, nil, nil
end

mod.snapMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_SNAP].modKey)
end

mod.copyMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_MOVE_COPY].modKey)
end

mod.overlapMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_MOVE_OVERLAP].modKey)
end
_G.overlapMod = overlapMod

mod.singleMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_MOVE_SINGLE].modKey)
end

mod.fullLaneMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_NEW_FULLLANE].modKey)
end

mod.preserveMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_NEW_PRESERVE].modKey)
end

mod.stretchMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_STRETCH].modKey)
end

mod.onlyAreaMod = function(someMods)
  someMods = someMods or currentMods
  return someMods:matchesFlags(modMappings[Keys.MODTYPE_MOVE_ONLYAREA].modKey)
end

mod.matchesWidgetMod = function(which)
  which = math.max(1, math.min(4, which))
  return widgetMods:matchesFlags(widgetMappings[which].modKey)
end

mod.setCursorMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_CLICK_SETCURSOR].modKey)
end

-- SLICER

mod.slicerTrimMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_SLICER_TRIM].modKey)
end

mod.slicerEndMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_SLICER_END].modKey)
end

mod.slicerVertLockMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_SLICER_VERTLOCK].modKey)
end

-- SLICER

-- PITCH BEND - base modifier checks
mod.shiftMod = function(someMods)
  return someMods and someMods:shift()
end

mod.optMod = function(someMods)
  return someMods and someMods:alt()
end

mod.cmdMod = function(someMods)
  return someMods and someMods:ctrl()
end

mod.ctrlMod = function(someMods)
  return someMods and someMods:super()  -- Actual Ctrl key on macOS
end

-- PITCH BEND
mod.pbDrawMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_PB_DRAW].modKey)
end

mod.pbCompExpMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_PB_COMPEXP].modKey)
end

mod.pbSnapToPitchMod = function(someMods)
  return mod.getMod(someMods, modMappings[Keys.MODTYPE_PB_SNAP_PITCH].modKey)
end

mod.pbSnapToGridMod = mod.shiftMod   -- uses global snap modifier
mod.pbSmoothDrawMod = mod.shiftMod   -- uses global snap modifier

Keys.mod = mod

return Keys
